Repository sgworkpass/mobile, pull requests merged in 2019-08, with the labels that each got.

#21 Feat/transfer api
  src/services/transferAPI.test.ts
  src/services/transferAPI.tsx
Labels: enhancement

#25 Feat/qr generator
  src/components/Camera/QRScanner.tsx
  src/components/QRGenerator/QrGenerator.tsx
  src/components/QRGenerator/QrGeneratorStyles.tsx
  src/components/SharePage/QrGenerator.tsx
  src/components/SharePage/index.tsx
  src/components/SharePage/obfuscateFields.ts
  src/components/SharePage/sharePageStyles.tsx
  src/components/TopBar/BarStyles.tsx
  src/components/profile/NoProfile.tsx
  src/components/profile/ProfileContainer.tsx
  src/components/profile/ProfileDetails.tsx
  src/components/profile/ProfilePassDetails.tsx
  src/services/qrHandler.test.tsx
  src/services/qrHandler.tsx
  src/services/transferAPI.tsx
Labels: enhancement

#37 feat/verification status distinction
  src/components/TopBar/VerifyingBar.tsx
  src/components/profile/ProfileContainer.tsx
  src/components/profile/ProfileName/index.tsx
  src/services/verificationService.ts
Labels: Ready to merge - pls review

#31 chore/refactor4
  __snapshots__/App.test.tsx.snap
  src/components/Camera/QRScanner.tsx
  src/components/Camera/ScanArea.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/TextRow.tsx
  src/components/Modals/InvalidQRModal.tsx
  src/components/Preview/PreviewContainer.tsx
  src/components/Preview/PreviewContainerStyles.ts
  src/components/Profile/NoProfile/NoProfile.tsx
  src/components/Profile/NoProfile/NoProfileStyles.tsx
  src/components/Profile/ProfileContainer.tsx
  src/components/Profile/ProfileDetails/DetailSection.tsx
  src/components/Profile/ProfileDetails/index.tsx
  src/components/Profile/ProfileImage/ProfileImageStyles.tsx
  src/components/Profile/ProfileImage/index.tsx
  src/components/Profile/ProfileName/ProfileNameStyles.tsx
  src/components/Profile/ProfileName/index.tsx
  src/components/Profile/ProfileSection.tsx
  src/components/Profile/VerifyProfile/VerifyProfileStyles.ts
  src/components/Profile/VerifyProfile/index.tsx
  src/components/Settings/DevDebug.tsx
  src/components/Settings/DevDebugSection/DevDeleteWorkpass.tsx
  src/components/Settings/DevDebugSection/DevStoreWorkPass.tsx
  src/components/Settings/SettingsTemplate.tsx
  src/components/Settings/styles.ts
  src/components/SharePage/QrGenerator.tsx
  src/components/SharePage/SharePageStyles.tsx
  src/components/SharePage/index.tsx
  src/components/Splash/index.tsx
  src/components/TopBar/BarStyles.tsx
  src/components/TopBar/VerifyingBar.tsx
  src/components/profile/VerifyProfile.tsx
  src/navigation/tabs/Profile/index.tsx
  src/navigation/tabs/Settings/index.tsx
  src/services/crypto/crypto.test.ts
  src/services/crypto/crypto.ts
  src/services/date/date.ts
  src/services/fileSystem.ts
  src/services/qrHandler/qrHandler.test.tsx
  src/services/qrHandler/qrHandler.tsx
  src/services/transferAPI/transferAPI.test.ts
  src/services/transferAPI/transferAPI.tsx
  src/services/verificationService/verificationService.test.ts
  src/services/verificationService/verificationService.ts
  src/state/index.tsx
Labels: Ready to merge - pls review

#43 RWS User Story Feature #2
  src/components/Camera/QRScanner.tsx
  src/components/SharePage/CustomFields.tsx
  src/components/SharePage/QrGenerator.tsx
  src/components/SharePage/index.tsx
  src/services/qrHandler.test.tsx
  src/services/qrHandler.tsx
Labels: Ready to merge - pls review

#42 feat/enablenoencrypt
  src/components/Camera/QRScanner.tsx
Labels: Ready to merge - pls review

#41 feat/profileselector
  src/assets/blurredtext.jpeg
  src/components/Camera/QRScanner.tsx
  src/components/Layout/TextRow.tsx
  src/components/Profile/ProfileDetails/index.tsx
  src/components/Profile/ProfileImage/ProfileImageStyles.tsx
  src/components/Profile/ProfileImage/index.tsx
  src/components/Profile/ProfileName/ProfileNameStyles.tsx
  src/components/Profile/ProfileName/index.tsx
  src/components/Profile/ProfileSection.tsx
  src/components/SharePage/CustomFields.tsx
  src/components/SharePage/ModalBody.tsx
  src/components/SharePage/QrGenerator.tsx
  src/components/SharePage/SharePageStyles.tsx
  src/components/SharePage/index.tsx
  src/components/SharePage/obfuscateFields.ts
  src/components/TopBar/VerifyingBar.tsx
  src/config/endpoints.ts
  src/navigation/BottomTabNavigator.tsx
  src/services/obfuscation/obfuscationHandler.test.ts
  src/services/obfuscation/obfuscationHandler.ts
  src/services/qrHandler/qrHandler.test.tsx
  src/services/qrHandler/qrHandler.tsx
  src/services/transferAPI/transferAPI.tsx
  src/services/verificationService/verificationService.test.ts
  src/services/verificationService/verificationService.ts
  src/test/fixtures/expiredCert.json
  src/test/fixtures/revokedCert.json
  src/test/fixtures/tamperedCert.json
  src/test/fixtures/validCert.json
Labels: Lint Errors - Pls fix, enhancement

#44 Bug/change document store
  src/services/obfuscation/obfuscationHandler.test.ts
  src/services/verificationService/verificationService.ts
  src/test/fixtures/expiredCert.json
  src/test/fixtures/revokedCert.json
  src/test/fixtures/tamperedCert.json
  src/test/fixtures/validCert.json
Labels: Ready to merge - pls review

#46 Added female deconstrutor
  src/components/Camera/ScannerPageStyleSheet.ts
  src/components/Profile/ProfileDetails/index.tsx
  src/components/Settings/DevDebugSection/DevStoreWorkPass.tsx
  src/components/TopBar/BarStyles.tsx
  src/services/obfuscation/obfuscationHandler.test.ts
  src/services/obfuscation/obfuscationHandler.ts
  src/services/qrHandler/qrHandler.test.tsx
  src/services/transferAPI/transferAPI.test.ts
Labels: Ready to merge - pls review

#39 Adding version
  .circleci/config.yml
  src/components/Settings/DevDebug.tsx
  src/config/index.ts
Labels: Work in progress
